!function(n){"object"==typeof exports&&"undefined"!=typeof module?module.exports=n():"function"==typeof define&&define.amd?define([],n):("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this).Clipboard=n()}(function(){return function g(l,k,h){function b(c,d){if(!k[c]){if(!l[c]){var e="function"==typeof require&&require;if(!d&&e)return e(c,!0);if(a)return a(c,!0);e=Error("Cannot find module '"+c+"'");throw e.code="MODULE_NOT_FOUND",e;}e=k[c]={exports:{}};
l[c][0].call(e.exports,function(a){var d=l[c][1][a];return b(d?d:a)},e,e.exports,g,l,k,h)}return k[c].exports}for(var a="function"==typeof require&&require,d=0;d<h.length;d++)b(h[d]);return b}({1:[function(g,l,k){var h=g("closest"),b=g("component-event"),a=["focus","blur"];k.bind=function(d,c,f,e,m){return-1!==a.indexOf(f)&&(m=!0),b.bind(d,f,function(a){a.delegateTarget=h(a.target||a.srcElement,c,!0,d);a.delegateTarget&&e.call(d,a)},m)};k.unbind=function(d,c,f,e){-1!==a.indexOf(c)&&(e=!0);b.unbind(d,
c,f,e)}},{closest:2,"component-event":4}],2:[function(g,l,k){var h=g("matches-selector");l.exports=function(b,a,d){for(b=d?b:b.parentNode;b&&b!==document;){if(h(b,a))return b;b=b.parentNode}}},{"matches-selector":3}],3:[function(g,l,k){g=Element.prototype;var h=g.matchesSelector||g.webkitMatchesSelector||g.mozMatchesSelector||g.msMatchesSelector||g.oMatchesSelector;l.exports=function(b,a){if(h)return h.call(b,a);for(var d=b.parentNode.querySelectorAll(a),c=0;c<d.length;++c)if(d[c]==b)return!0;return!1}},
{}],4:[function(g,l,k){var h=window.addEventListener?"addEventListener":"attachEvent",b=window.removeEventListener?"removeEventListener":"detachEvent",a="addEventListener"!==h?"on":"";k.bind=function(b,c,f,e){return b[h](a+c,f,e||!1),f};k.unbind=function(d,c,f,e){return d[b](a+c,f,e||!1),f}},{}],5:[function(g,l,k){function h(){}h.prototype={on:function(b,a,d){var c=this.e||(this.e={});return(c[b]||(c[b]=[])).push({fn:a,ctx:d}),this},once:function(b,a,d){var c=this,f=function(){c.off(b,f);a.apply(d,
arguments)};return this.on(b,f,d)},emit:function(b){var a=[].slice.call(arguments,1),d=((this.e||(this.e={}))[b]||[]).slice(),c=0,f=d.length;for(c;f>c;c++)d[c].fn.apply(d[c].ctx,a);return this},off:function(b,a){var d=this.e||(this.e={}),c=d[b],f=[];if(c&&a)for(var e=0,m=c.length;m>e;e++)c[e].fn!==a&&f.push(c[e]);return f.length?d[b]=f:delete d[b],this}};l.exports=h},{}],6:[function(g,l,k){k.__esModule=!0;var h=function(){function b(a,b){for(var c=0;c<b.length;c++){var f=b[c];f.enumerable=f.enumerable||
!1;f.configurable=!0;"value"in f&&(f.writable=!0);Object.defineProperty(a,f.key,f)}}return function(a,d,c){return d&&b(a.prototype,d),c&&b(a,c),a}}();g=function(){function b(a){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");this.resolveOptions(a);this.initSelection()}return b.prototype.resolveOptions=function(){var a=0>=arguments.length||void 0===arguments[0]?{}:arguments[0];this.action=a.action;this.emitter=a.emitter;this.target=a.target;this.text=a.text;this.trigger=
a.trigger;this.selectedText=""},b.prototype.initSelection=function(){if(this.text&&this.target)throw Error('Multiple attributes declared, use either "target" or "text"');if(this.text)this.selectFake();else{if(!this.target)throw Error('Missing required attributes, use either "target" or "text"');this.selectTarget()}},b.prototype.selectFake=function(){var a=this;this.removeFake();this.fakeHandler=document.body.addEventListener("click",function(){return a.removeFake()});this.fakeElem=document.createElement("input");
this.fakeElem.style.position="absolute";this.fakeElem.style.left="-9999px";this.fakeElem.setAttribute("readonly","");this.selectedText=this.fakeElem.value=this.text;document.body.appendChild(this.fakeElem);this.fakeElem.select();this.copyText()},b.prototype.removeFake=function(){this.fakeHandler&&(document.body.removeEventListener("click"),this.fakeHandler=null);this.fakeElem&&(document.body.removeChild(this.fakeElem),this.fakeElem=null)},b.prototype.selectTarget=function(){if("INPUT"===this.target.nodeName||
"TEXTAREA"===this.target.nodeName)this.target.select(),this.selectedText=this.target.value;else{var a=document.createRange(),b=window.getSelection();a.selectNodeContents(this.target);b.addRange(a);this.selectedText=b.toString()}this.copyText()},b.prototype.copyText=function(){var a=void 0;try{a=document.execCommand(this.action)}catch(b){a=!1}this.handleResult(a)},b.prototype.handleResult=function(a){a?this.emitter.emit("success",{action:this.action,text:this.selectedText,trigger:this.trigger,clearSelection:this.clearSelection.bind(this)}):
this.emitter.emit("error",{action:this.action,trigger:this.trigger,clearSelection:this.clearSelection.bind(this)})},b.prototype.clearSelection=function(){this.target&&this.target.blur();window.getSelection().removeAllRanges()},h(b,[{key:"action",set:function(){if(this._action=0>=arguments.length||void 0===arguments[0]?"copy":arguments[0],"copy"!==this._action&&"cut"!==this._action)throw Error('Invalid "action" value, use either "copy" or "cut"');},get:function(){return this._action}},{key:"target",
set:function(a){if(void 0!==a){if(!a||"object"!=typeof a||1!==a.nodeType)throw Error('Invalid "target" value, use a valid Element');this._target=a}},get:function(){return this._target}}]),b}();k["default"]=g;l.exports=k["default"]},{}],7:[function(g,l,k){function h(a){return a&&a.__esModule?a:{"default":a}}function b(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,
enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}k.__esModule=!0;var a=g("./clipboard-action"),d=h(a),a=g("delegate-events"),c=h(a);g=g("tiny-emitter");g=function(a){function e(b,c){if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");a.call(this);this.resolveOptions(c);this.delegateClick(b)}return b(e,a),e.prototype.resolveOptions=function(){var a=0>=arguments.length||void 0===arguments[0]?{}:arguments[0];
this.action="function"==typeof a.action?a.action:this.setAction;this.target="function"==typeof a.target?a.target:this.setTarget;this.text="function"==typeof a.text?a.text:this.setText},e.prototype.delegateClick=function(a){var b=this;c["default"].bind(document.body,a,"click",function(a){return b.initialize(a)})},e.prototype.initialize=function(a){this.clipboardAction&&(this.clipboardAction=null);this.clipboardAction=new d["default"]({action:this.action(a.delegateTarget),target:this.target(a.delegateTarget),
text:this.text(a.delegateTarget),trigger:a.delegateTarget,emitter:this})},e.prototype.setAction=function(a){return a.hasAttribute("data-clipboard-action")?a.getAttribute("data-clipboard-action"):void 0},e.prototype.setTarget=function(a){if(a.hasAttribute("data-clipboard-target"))return a=a.getAttribute("data-clipboard-target"),document.querySelector(a)},e.prototype.setText=function(a){return a.hasAttribute("data-clipboard-text")?a.getAttribute("data-clipboard-text"):void 0},e}(h(g)["default"]);k["default"]=
g;l.exports=k["default"]},{"./clipboard-action":6,"delegate-events":1,"tiny-emitter":5}]},{},[7])(7)});
